type User {
  id: ID!
  username: String!
  role: String!
  created: Date!
}

input UserInput {
  username: String!
  password: String!
}

type Query {
  currentUser: User
}

type Mutation {
  register(input: UserInput!): User!
  signIn(input: UserInput!): User!
}
